# Einstein Notation and np.einsum

## Useful Resources
- [NumPy einsum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html)
- [A basic introduction to NumPy's einsum](http://ajcr.net/Basic-guide-to-einsum/)

In [1]:
import numpy as np

## What is Einstein notation?
Einstein notation is a notational convention that simplifies expressions containing vectors, matrices, or tensors.

"I have made a great discovery in mathematics; I have suppressed the summation sign every time that the summation must be made over an index which occurs twice..." ~ Einstein (Kollros 1956; Pais 1982, p. 216).

### Vector Example
Let's have two three dimensional vectors $\textbf{A}$ and  $\textbf{B}$:
$$\textbf{A} = A_x \hat{x} + A_y \hat{y} + A_z \hat{z}$$
$$\textbf{B} = B_x \hat{x} + B_y \hat{y} + B_z \hat{z}$$

If we wanted to do the dot product of $\textbf{A}$ and  $\textbf{B}$ we would have:
$$\textbf{A}\cdot \textbf{B} = A_x B_x + A_y B_y + A_z B_z$$

This gives us a scalar that is the sum of the products:
$$\textbf{A}\cdot \textbf{B} = \sum_{i=1}^{N} A_i B_i \quad \textrm{where} \quad N = 3$$

In [2]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

In [3]:
np.sum(np.multiply(A, B))

32

In [4]:
np.einsum('i,i->', A, B)

32

### Let's look at a 3x3 example

In [5]:
C = np.random.rand(3, 3)
D = np.random.rand(3, 3)

print(C)
print('\n')
print(D)

[[0.44892352 0.23946046 0.3720617 ]
 [0.29549156 0.0521187  0.5270508 ]
 [0.27981144 0.73042791 0.9594615 ]]


[[0.16955709 0.30609099 0.08329563]
 [0.0690296  0.76714205 0.89986847]
 [0.15000005 0.35051006 0.47822482]]


In [6]:
np.sum(np.multiply(C, D)) 

1.4718948471833324

In [7]:
%%timeit
np.sum(np.multiply(C, D)) 

3.77 µs ± 90.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
np.einsum('ij,ij->', C, D)

1.4718948471833326

In [9]:
%%timeit
np.einsum('ij,ij->', C, D)

1.93 µs ± 15.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## What can Einstein notation do?

| String | np equiv. | Description|
|-|-|-|
| 'ij', C | C | returns C |
| 'ji', C | C.T | transpose of C |
| 'ii->i', C | np.diag(C) | returns diagonal |
| 'ii', C | np.trace(C) | returns trace |
| 'ij->', C | np.sum(C) | sum of C |
| 'ij->j', C | np.sum(C, axis=0) | sum down columns of C |
| 'ij,ij->ij', C, D | C * D | element-wise multiplication of C and D |
| 'ij,jk', C, D | C.dot(D) | matrix multiplication of C and D |

[For more](http://ajcr.net/Basic-guide-to-einsum/)

## Try your hand at Einstein notation
- sum along rows of C
- C * D.T
- inner product of C and D

#### Sum along rows of C

In [10]:
np.einsum('ij->i', C)

array([1.06044568, 0.87466107, 1.96970085])

#### C * D.T

In [11]:
np.einsum('ij,ji->ij', C, D)

array([[0.07611817, 0.01652986, 0.05580928],
       [0.09044731, 0.03998245, 0.18473661],
       [0.02330707, 0.65728904, 0.4588383 ]])

#### Inner product of C and D

In [12]:
np.einsum('ij,kj->ik', C, D)

array([[0.18040597, 0.5494958 , 0.32920099],
       [0.10995678, 0.53465651, 0.31464066],
       [0.35094037, 1.44304639, 0.75683236]])

### Dot Product
Time 4 different ways a dot product can be performed

In [13]:
%%timeit
C @ D

865 ns ± 2.93 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
%%timeit
np.dot(C, D)

917 ns ± 4.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%%timeit
C.dot(D)

897 ns ± 5.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
%%timeit
np.einsum('ij,jk', C, D)

1.95 µs ± 8.14 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
